- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/main/res/layout/headers.xml
- app/src/main/res/layout/subtotal_num_dem.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
> Footer color and padding, Header padding reduced

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardDetailsFragment.java
> No more swiping header|footer

- .idea/gradle.xml
- .idea/misc.xml
- app/app.iml
- app/src/main/res/layout/assessment_footer.xml
- app/src/main/res/layout/form_custom.xml
- app/src/main/res/layout/iqatab.xml
- app/src/main/res/layout/uncheckeable_radiobutton.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
> Fix some xml lint errors

- .idea/gradle.xml
- .idea/misc.xml
- app/app.iml
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/CreateSurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardDetailsFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
DashbaordDetailsFragment loads surveys from a Service (running in the background).
The SurveyService will used for other background operations related to Surveys (this is yet to be done).
> Dashboard background service

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/CompositeScore.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardDetailsFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/java/org/eyeseetea/malariacare/views/EditCard.java
- app/src/main/java/org/eyeseetea/malariacare/views/TextCard.java
- app/src/main/java/org/eyeseetea/malariacare/views/UncheckeableRadioButton.java
- app/src/main/res/layout/survey.xml
Issues #223 , #84 
Some refactoring was required to fit SurveyActivity + Adapters + SurveyService.
Now Dashboard and Survey load faster than before.
> Survey background service

- app/src/androidTest/java/org/eyeseetea/malariacare/test/DashboardDetailsActivityExpressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/MalariaEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SettingsEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SurveyChecksEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SurveyEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SurveyScoresEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/IntentServiceIdlingResource.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/MalariaEspressoActions.java
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardDetailsFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/java/org/eyeseetea/malariacare/views/EditCard.java
- app/src/main/java/org/eyeseetea/malariacare/views/TextCard.java
- app/src/main/java/org/eyeseetea/malariacare/views/UncheckeableRadioButton.java
Issue #217 , includes some refactor related to visual preferences that was required in order to ease testing.
As a positive lateral effect, tabs and layouts depending on Preferences load slightly faster. :D.
> Broken tests with service

- app/src/androidTest/java/org/eyeseetea/malariacare/test/DashboardDetailsActivityExpressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/MalariaEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SettingsEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SurveyChecksEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SurveyEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/SurveyScoresEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/IntentServiceIdlingResource.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/MalariaEspressoActions.java
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardDetailsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardDetailsFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/java/org/eyeseetea/malariacare/views/EditCard.java
- app/src/main/java/org/eyeseetea/malariacare/views/TextCard.java
- app/src/main/java/org/eyeseetea/malariacare/views/UncheckeableRadioButton.java
- app/src/main/res/transition/anim_slide_in_left.xml
- app/src/main/res/transition/anim_slide_in_right.xml
- app/src/main/res/transition/anim_slide_out_left.xml
- app/src/main/res/transition/anim_slide_out_right.xml
- app/src/main/res/values/styles.xml
Solves issue #167 
Recommended to solve previous pull request before this one.
> Transitions

- .idea/gradle.xml
- .idea/misc.xml
- .idea/modules.xml
- app/app.iml
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardDetailsFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/res/xml/pref_general.xml
> Remove subscore bar

- app/src/main/java/org/eyeseetea/malariacare/database/model/Header.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/CustomIQTABAdapter.java
- app/src/main/res/layout/integer.xml
adding optimization for children-parent show/hide logic
> Childparent logic optimization

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
After testing it, it looks like we're changing to "Prepared to send" state when we're almost at 100% . But that bug will be treated in a different issue
> percentage completion bug solved

- app/src/edsGhana/res/values/strings.xml
- app/src/edsMalawi/res/values/strings.xml
- app/src/edsMozambique/res/values/strings.xml
- app/src/edsTanzania/res/values/strings.xml
- app/src/edsZambia/res/values/strings.xml
- app/src/hnqis/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/res/layout/login_layout.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
login screen before removing it from app start
> Login changes

- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
The user experience has improved a lot
> the preload task is now a service launched after first tab is loaded

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
> Bug with comp. scores and custom tabs solved!

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/FeedbackActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/feedback/CompositeScoreFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/database/feedback/Feedback.java
- app/src/main/java/org/eyeseetea/malariacare/database/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/feedback/QuestionFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/CompositeScore.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/res/drawable/circle_shape_amber.xml
- app/src/main/res/drawable/circle_shape_green.xml
- app/src/main/res/drawable/circle_shape_red.xml
- app/src/main/res/layout/feedback.xml
- app/src/main/res/layout/feedback_composite_score_row.xml
- app/src/main/res/layout/feedback_question_row.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Feedback sent

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
> Dashboard refresh after sent

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Not answered questions go amber and the label is not answered

- app/src/main/java/org/eyeseetea/malariacare/CreateSurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/LocationMemory.java
- app/src/main/java/org/eyeseetea/malariacare/layout/listeners/SurveyLocationListener.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
> Pick location on create survey

- app/src/main/java/org/eyeseetea/malariacare/FeedbackActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/feedback/CompositeScoreFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/database/feedback/QuestionFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/res/layout/feedback.xml
- app/src/main/res/layout/feedback_composite_score_row.xml
- app/src/main/res/layout/feedback_question_row.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/color.xml
- app/src/main/res/values/strings.xml
> Feedback gui changes

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
> changed string

- app/src/main/java/org/eyeseetea/malariacare/database/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
> Calculates main score in prefeedback, calculated spinner read only

- app/src/main/java/org/eyeseetea/malariacare/database/feedback/FeedbackBuilder.java
> Hidden children questions show NO feedback

- app/src/main/java/org/eyeseetea/malariacare/database/feedback/FeedbackBuilder.java
last bug correction incorporation into development
> bringing last hotfix to development

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
> Fixes countRequiredByProgram and optimizes match feature

- app/src/main/java/org/eyeseetea/malariacare/database/feedback/QuestionFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/res/layout/feedback_question_row.xml
> Hot fixes r11 scores

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.program.js
> Javascript compatibility issue with api 17

- LICENSE-MIT
- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.program.js
- app/src/main/assets/dashboard/sent.month.js
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/FacilityRowData.java
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/PieProgramBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/SentSurveysBuilder.java
- app/src/main/res/layout/fragment_dashboard.xml
- app/src/main/res/raw-es/gpl.txt
- app/src/main/res/raw-fr/gpl.txt
- app/src/main/res/raw/gpl.txt
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-w820dp/dimens.xml
- app/src/main/res/values/strings.xml
> r12 charts bugfixing

- app/src/main/java/org/eyeseetea/malariacare/FeedbackActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Score.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Main score stored in db, empty surveys not sent

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushResult.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Better control over push error messages, success i18n

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.program.js
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/PieProgramBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/PieProgramData.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushResult.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Closes #257, #514 (minor adjustments to charts)
> Review r12

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.tabgroup.js
- app/src/main/assets/dashboard/table.facilities.js
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/FacilityTableBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/PieTabGroupBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/monitor/PieTabGroupData.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
> Closes #478,#514

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- settings.gradle
> Push, login, logout, back to flow

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/CreateSurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/FeedbackActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
> Pull working after relogin, logout async completed

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/UserAccountExtended.java
> Loads current logged user into our User table

- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
Commit 57cc49b20043e0c303a4ea09d99610e169dc0738, that we needed to cherry-pick had .idea files. To cherry-pick that, there was only 2 solutions:
- Execute a git-rebase of that commit and the following (that corrected that problem), but that would mean picking an ugly solution.
- Manually introduce the change. For this situation, as the change was very very little, I've chosen the second one
> manual cherry-pick from ugly commit 

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/CompositeScoreBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
> Adds output field to answer

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
At the end we said that the completionDate is the date of send.
I removed update sent surveys after set completed becouse dont do nothing. 
I added prepareSurveyCompleteDate to set the actual date to the survey to be sent
I think we can change:
if(answeredRatio.isCompleted()) {
this.setStatus(Constants.SURVEY_COMPLETED);
this.setCompletionDate(new Date());
}else{
this.setStatus(Constants.SURVEY_IN_PROGRESS);
this.setCompletionDate(this.eventDate);
}
to
if(answeredRatio.isCompleted()) {
this.setStatus(Constants.SURVEY_COMPLETED);
}else{
this.setStatus(Constants.SURVEY_IN_PROGRESS);
}
this.setCompletionDate(new Date());
I can´t try this changes in visitors_try at this moment. I can´t sent surveys.
> CompletionDate is the date of send

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/IConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataValueExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Pull values and surveys

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullProgressStatus.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/res/layout/activity_progress.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-w820dp/dimens.xml
- app/src/main/res/values/strings.xml
> Uses its own progress activity to pull data

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
> Push before pull

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Match.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/QuestionRelation.java
> Fix question relations

- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/res/layout/activity_progress.xml
- app/src/main/res/values/strings.xml
@ifoche 
Added pulling control with preferenceshared (if you don´t like i remove it).
Fixed the progresactivity dialog as models dialog.
closes #585
> Screen switches off crash

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- Push surveys via sdk before pull (#594)
- Removes "OuiNon (to be removed)" exception in ICM (#603)
> Answers options icm

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Added orgUnitLevel "Zone" string in all the languages

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/CompositeScoreBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OptionSetExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Answer.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Option.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Closes #610 and #615

- app/src/main/java/org/eyeseetea/malariacare/CreateSurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration1RestartDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Answer.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/CompositeScore.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Header.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Match.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Option.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnitLevel.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Program.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/QuestionOption.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/QuestionRelation.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Score.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/TabGroup.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/User.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Lazy dbflow

- app/src/hnqis/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
> forward order control dataElement added in push

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
> survey state change when imported questions blocked by Exception

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/res/values-fr/strings.xml
> filtered last survey by program+orgUnit

- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/res/values/settings.xml
Closes #626.
Some minor refactor was required in **PopulateDB** in order to work properly in addition with lazy loading.
> By pass pull from server via xml config

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
I can´t reproduce the issue.
I think if the application go to "on pause" the pull fails, and it should go to login, but if the application change to onPause during the push it should go to the dashboard.
I added a job cancel for the metadata, and this branch should be merged with the sdk changes 
https://github.com/EyeSeeTea/dhis2-android-sdk/pull/7
Closes #650
> Fix cancel

- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration1RestartDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Answer.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Option.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
> Question type

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Assess tab

- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/CompositeScoreBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/AttributeExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataValueExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OptionExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OptionSetExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OrganisationUnitExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/ProgramExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/ProgramStageExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/ProgramStageSectionExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/UserAccountExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Match.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/QuestionRelation.java
Indexing to avoid SQlite errors and save a few seconds
> a few seconds saved indexing queries

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Program.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/MonitorFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/res/layout/assessment_sent_header.xml
- app/src/main/res/layout/tab_dashboard.xml
At this moment, we can look the unsent completed surveys with score in the dashboardSentFragment.
closes #637
> Improve tab

- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration1RestartDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/MigrationAddCompulsory.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/SurveyAnsweredRatio.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Compulsory questions

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/res/layout/assessment_sent_header.xml
@ifoche i detected a bug, in API16 (the click for sentfragments order was not working). This branch resolve it.
> Fix onclick order api16

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Fix push background

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.tabgroup.js
- app/src/main/assets/dashboard/sent.month.js
- app/src/main/assets/dashboard/table.facilities.js
Closes #691 
Finally... i used  only  CSS to make the circles.
And i changed the big circle position like in the pdf.
I only can´t change the black "arrows" in the big circle.
> Change monitor tab

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
**important** This PR should be apply only for 2.21 sdk
> ProgramType moves in sdk 2.21

- app/src/edsGhana/assets/Answers.csv
- app/src/edsGhana/assets/Headers.csv
- app/src/edsGhana/assets/Options.csv
- app/src/edsGhana/assets/Questions.csv
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/QuestionRelation.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
> R10k bugfixing

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
> Hide planning tab

- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/MigrationAddEventUid.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Persist eventsuid in db

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
closes #737 
(I added the strings for dialog_sent_survey_on_refresh_metadata too).
> Check compulsory question before pull metadata

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
> Load AlarmPushReceiver at least one time in the dashboard init.

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
closes #759
I revise the regexp too.
> Feedback changes

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/views/ReadonlyPreference.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
> Dhis server, user, pass goes back to login from settings

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OrganisationUnitExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/ProgramExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnitProgramRelation.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Program.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/PlannedSurvey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/SurveyPlanner.java
> Productivity as a combination of attributes from orgunit and program

- app/src/androidTest/java/org/eyeseetea/malariacare/test/login/LoginTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullCancelTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullErrorTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullOKTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullTranslationSDKToAppDBTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushOKTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/SDKTestUtils.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnit.java
> Productivity test bug

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/sent.month.js
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/PlannedHeader.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/filters/FilterOrgUnitArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/filters/FilterProgramArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/PlannedAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/res/layout/assessment_record.xml
- app/src/main/res/layout/assessment_sent_record.xml
- app/src/main/res/layout/create_survey_fragment.xml
- app/src/main/res/layout/create_survey_org_unit_item_fragment.xml
- app/src/main/res/layout/main_header.xml
- app/src/main/res/layout/tab_dashboard.xml
- app/src/main/res/values/color.xml
- app/src/main/res/values/dimens.xml
Closes #793 
One comment about the last point. I edit the Overdue row color too(I think you maybe say never assessed but want said overdue)
> Fix ui feedback

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataValueExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OptionExtended.java
Closes #778 (requires sdk to be updated with option_attributes stuff too)
> Loads option factor via OptionAttributeValue 'OF'

- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullCheckMaxEvents.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/SDKTestUtils.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
> Change the event limit from 200 to 3

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
> Fix plan hide problems

- app/src/main/res/values/strings.xml
> Change "WIN" to "PASS"

- app/src/androidTest/java/org/eyeseetea/malariacare/test/AssessAction/AssessDeleteTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/SDKTestUtils.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
> Restore delete dialog

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.tabgroup.js
Closes #812 
Comment:
I only change the pie chart colors(and pie table colors), not the all assessment table colors(target blue and  Assessment undertaken green), becouse i think it is other view.
Ok other problem: i set the colors from feedback, but i will change this colors in #814 .
Not take time, but maybe is good not forget it.
> Monitor colors

- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
> Fix colors in improve and feedback(blue background)

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/filters/FilterOrgUnitArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/filters/FilterProgramArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/general/OrgUnitArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/general/ProgramArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/general/TabGroupArrayAdapter.java
- app/src/main/res/values/dimens.xml
> Add and increase custom padding in the filters and in create surveys to

- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/SDKTestUtils.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Alert dialog when asssessment is completed

- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
> Fix crash on click in a link in feedbackfragment

- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/QuestionFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
> Feedback label bold

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/PlannedAdapter.java
> Make the comment of a date reschedule optional

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/PlannedAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
Closes #853
I use the planing tab format ("Mar/7/2016")
But maybe you want the last format("05/7/2016")
(And is not american format, is the mobile format, maybe you are looking other format in your mobile).
> Make date format as planning format

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Show survey name on remove

- app/src/main/res/xml/pref_general.xml
> show numdem made the last option in preferences

- app/src/main/assets/dashboard/table.facilities.js
- app/src/main/java/org/eyeseetea/malariacare/database/utils/monitor/FacilityRowData.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/monitor/PieTabGroupBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/monitor/SentSurveysBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
Fix dates to point to event date and some typos
> Fix complete dates

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
Closes #873
@ifoche  i created the issue #873 becouse i found this simple bug.
I only add the reloadData like the others fragments to fix it.
> Bug removed survey in planning

- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
Closes  #875 
@ifoche 
I was trying the app and i look this "bug".
Maybe you want do PR, maybe not.
I hope it´s not too late.
> Added try{}catch to prevent the app crash if the user don´t wait for the

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/MonitorFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Monitor fragment with complete surveys too

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
> Fix bug in the feedback header score colors.

- app/src/hnqis/res/values/strings.xml
- app/src/main/res/layout/login_layout.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Remove the default url from the login, and show hint "Server dhis2"

- app/src/main/res/layout/feedback.xml
> Resize feedback score

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/res/layout/assessment_sent_record.xml
- app/src/main/res/values/dimens.xml
Closes #893
It was removed in [773b10359e5c1a984cc981796061b6057e6ae829](https://github.com/EyeSeeTea/malariapp/commit/773b10359e5c1a984cc981796061b6057e6ae829)
I fixed the visible facility name, because if we have a long list, it was shown in the middle of the list.
It is shown in the first survey now.
> Add padding improve list

- app/src/eds/java/org/eyeseetea/malariacare/utils/VariantSpecificUtils.java
- app/src/hnqis/java/org/eyeseetea/malariacare/utils/VariantSpecificUtils.java
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- Variant-dependent code separated using variant file structure
- Unavailable string in lastcommit translated into different languages
- Refactor of an if-else at AlarmPushReceiver
- Refactor of COMPLETION_DATE_FORMAT and SIMPLE_DATE_FORMAT at EventExtended
> Little refactors

- app/src/eds/res/values/strings.xml
- app/src/hnqis/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/ControlDataElement.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/res/values/strings.xml
Closes #913
It needs [sdk branch](https://github.com/EyeSeeTea/dhis2-android-sdk/tree/pull_all_programDataelements)
> Pull controldataelements

- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullCheckMaxEvents.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
Closes #911 
And work with [event_query_by_date](https://github.com/EyeSeeTea/dhis2-android-sdk/tree/event_query_by_date) branch
> Pull events from date

- app/src/edsZambia/assets/CompositeScores.csv
Removing the 'Speciation' comp. score from Slide Rechecking.
> Removing comp. score

- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
> protection from badly configured server regarding CS added

- app/src/androidTest/java/org/eyeseetea/malariacare/test/AssessAction/AssessDeleteTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/logout/WipeDataOnLogout.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullCheckMaxEvents.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullOKTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/pull/PullTranslationSDKToAppDBTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushConflictTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushErrorTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushOKTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/SDKTestUtils.java
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataValueExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/OrganisationUnitExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/ProgramExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
> Remove the sdk data on logout

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
> Saved the event creation date after push

- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushErrorTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushOKTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/utils/SDKTestUtils.java
- app/src/androidTest/java/org/eyeseetea/malariacare/testEds/modify/ModifySurveyTest.java
- app/src/eds/java/org/eyeseetea/malariacare/utils/VariantSpecificUtils.java
- app/src/hnqis/java/org/eyeseetea/malariacare/utils/VariantSpecificUtils.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/MigrationAddValueDate.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/CreateSurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/network/NetworkUtils.java
- app/src/main/java/org/eyeseetea/malariacare/network/PullClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/QueryFormatterUtils.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Create or modify surveys ct

- app/src/eds/res/layout/create_survey_fragment_program_options.xml
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/CreateSurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/res/layout/create_survey_fragment_program_options.xml
Closes #928
This branch needs :  [sdk PR](https://github.com/EyeSeeTea/dhis2-android-sdk/pull/47)
> Fix orgunitlevels

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/ProgramExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/TabGroup.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/PlannedItemBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/SurveyPlanner.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/CreateSurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/filters/FilterTabGroupArrayAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/ModuleController.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Pull tabgroups

- app/src/androidTest/java/org/eyeseetea/malariacare/test/push/PushErrorTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/testEds/modify/ModifySurveyTest.java
- app/src/eds/java/org/eyeseetea/malariacare/utils/VariantSpecificUtils.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/network/PullClient.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Closes #951
This branch should work with the ivan last PR( i test it).
> Eds custom tabs fix lastsurvey

- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/AssessModuleController.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/DashboardController.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/ImproveModuleController.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/ModuleController.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/PlanModuleController.java
> Adds transitions x convention (slide left or right)

- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/TabGroupBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Create fake tabgroup if not exist

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabInVisibilityState.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabSelectedItem.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabViewHolder.java
> Optimize toggle visibility

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/utils/AUtils.java
- app/src/main/res/layout/create_survey_fragment.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Eds visual bugs

- app/src/eds/res/raw/settings.json
- app/src/hnqis/res/raw/settings.json
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/builder/AppSettingsBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/config/DatabaseSettings.java
- app/src/test/java/org/eyeseetea/malariacare/layout/dashboard/config/AppSettingsTest.java
> Retrieve full hierarchy or just leaves depending on settings.json

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
> Avoid NPE while pulling

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/EventToSurveyBuilder.java
> Checking custom tabs

- app/src/main/java/org/eyeseetea/malariacare/fragments/CreateSurveyFragment.java
> Bug custom tabs repeated oncreate levels

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/PlannedSurvey.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/MonitorFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Prevent CS crash

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedFragment.java
> Prevent add filter "all programs" more than one time

- app/src/main/assets/dashboard/sent.month.js
> Fix, show all assessment if only have one program.

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/planning/PlannedSurvey.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/MonitorFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
closes #1018 
Checked root CS.
Fixed: If a question have a CS and that CS is the parent CS, the question is shown in the feedback too.
> Survey without cs show all questions

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
closes #1019 and closes #1020
The numerator value of a question without it is the denominator value now.
And the denominator value is the question denominator value or 0 if not exist.
> Survey without cs fix numerator denominator

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Modify dialog_info_delete_survey strings

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/DashboardController.java
> Feature ct prompt after mark as completed

- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/AssessModuleController.java
> Fixed the blank surveyFragemnt on num/denum visibility change

- app/src/eds/res/values-es/strings.xml
- app/src/eds/res/values-fr/strings.xml
- app/src/eds/res/values-pt/strings.xml
- app/src/eds/res/values/strings.xml
> Change eds strings (sent asssessment to complete assessment)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> modify dialog_content_existing_survey

- app/src/eds/res/raw/settings.json
- app/src/hnqis/res/raw/settings.json
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/builder/AppSettingsBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/config/DashboardListFilter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/config/DashboardSettings.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/deserializers/DashboardListFilterDeserializer.java
- app/src/main/res/xml/pref_general.xml
- app/src/surveillance/res/raw/settings.json
> Feature add list filter option

- app/src/androidTest/java/org/eyeseetea/malariacare/test/CreateSurveyEspressoTest.java
- app/src/androidTest/java/org/eyeseetea/malariacare/test/MalariaEspressoTest.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/CompositeScoreFeedback.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/CreateSurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/ATabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/CompositeScoreAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/PlannedAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushUtils.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/java/org/eyeseetea/malariacare/utils/AUtils.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
> Bug hnqis compositescore map

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/ATabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/AssessModuleController.java
> Feature ct long click

- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
> Bug ct all questions appearing in feedback

- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/FeedbackBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
> Bug remove questions without cs from feedback

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
> Fix datapiker bug

- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabViewHolder.java
> prevent crash on read only scrolling

- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/OrgUnitLevel.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Program.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Feature alphabetical order on survey dropdowns

- app/src/eds/res/values/donottranslate.xml
> Change eds app name to eds2

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Closes #1083 
I can't test it in the real server(https://eds-ke-dev.bao[...] its down), 
i tested it in a modified local database.
> Feature add clear button on datepiker

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Bug customtabs events with blank date

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Bug blank eventdates

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
> hide week numbers in datepicker

- app/src/main/res/layout/vertical_assess_layout.xml
- app/src/main/res/layout/vertical_improve_layout.xml
> Fix bug with padding framelayout dimens if the app is launched on

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/feedback/DashboardSentBundle.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Bug feedback crash

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
closes #1110  
(to reproduce this bug in the emulator: send complete a lot of surveys in a flew seconds)
> Bug send some survey if push is working crash

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
> show tabGroup instead of program name

- app/src/edsGhana/assets/OrgUnitLevels.csv
> change OU levels labels

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
> Bug ct push locker and send all surveys

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ANumDenRecord.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
Closes #1117 in Custom tabs
I updated "custom tabs Score register test" branch too.
> Feature score register takes only compulsory or anwsered questions

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ANumDenRecord.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
closes #1117 
merge with development.
> Feature scoreregister takes only compulsory and answered questions in hnqis

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
> Fix- gets survey feedback from filtered list

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/CompositeScoreBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
> Sets the CompositeScore order from Order attribute

- app/src/main/res/layout/main_header.xml
- app/src/main/res/values/dimens.xml
> Feature: make surveyfragment arrow bigger

- app/src/main/assets/dashboard/dashboard.html
- app/src/main/assets/dashboard/pie.tabgroup.js
- app/src/main/assets/dashboard/sent.month.js
- app/src/main/assets/dashboard/table.facilities.js
- app/src/main/assets/dashboard/translated.messages.js
- app/src/main/java/org/eyeseetea/malariacare/database/utils/monitor/MonitorMessagesBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/MonitorFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Init monitor strings via javascript

- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Match.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/java/org/eyeseetea/malariacare/utils/AUtils.java
- app/src/main/java/org/eyeseetea/malariacare/views/CustomEditText.java
- app/src/main/java/org/eyeseetea/malariacare/views/CustomRadioButton.java
- app/src/main/java/org/eyeseetea/malariacare/views/CustomTextView.java
- app/src/main/java/org/eyeseetea/malariacare/views/TypefaceCache.java
- app/src/main/res/layout/ddl.xml
- app/src/main/res/layout/label.xml
- app/src/main/res/layout/radio.xml
> Parent child optimization

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
> Moves listener to radiobutton to avoid duplicated events

- app/src/main/assets/dashboard/pie.tabgroup.js
- app/src/main/assets/dashboard/table.facilities.js
> Fix monitor pie bug: remove pie chart if a program is empty

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/ATabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
Closes #1145 (so far, dropdown disabled yet to be done)
@adrianq done.
> Scroll optimization

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
Closes #1160
(to test this branch is necessary merge this  [branch](https://github.com/EyeSeeTea/malariapp/tree/feature-add_compusory_childrens_funcionality)).
> Feature add compusory childrens funcionality

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Closes #1166
This problem happens with the program _XX HNQIS Test in hnqis-dev-ci.psi-mis.org
I created a "user role" with that program to test it more faster.(I added that "user role" to idelcano_test)
> Feature show exception on attribute code null

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/MigrationAddOptionUid.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Option.java
Closes #1158 
this branch needs this sdk update:  https://github.com/EyeSeeTea/dhis2-android-sdk/pull/64
@ifoche maybe you preferes merge the custom_tab [branch](https://github.com/EyeSeeTea/malariapp/tree/feature-ct_multilevel_parents)( it have a little change in db migration number)
I used the program: iwiOQoq5Pl8 ICM
I added two new attributes:
https://hnqis-dev-ci.psi-mis.org/api/attributes/o6Qs33s2dSG  code="DEQuestionParents" 
https://hnqis-dev-ci.psi-mis.org/api/attributes/P7JrYb1ALTT   code="DEQuestionParentOptions"
I tested this feature in hnqis-dev-ci with the follow dataelemens:
Child
https://hnqis-dev-ci.psi-mis.org/api/dataElements/jSlshy864LD
Parents:
https://hnqis-dev-ci.psi-mis.org/api/attributes/o6Qs33s2dSG  code="DEQuestionParents" 
<value>qmGnowBqwuz,wl65ofYk8Aj</value> …
> Feature multilevel child parent relations

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedFragment.java
@ifoche 
I did detected and fixed this bug.
When you exit and come back from the app(using on resume) the plannedfragment and dashboardunsent lists aren't shown.
> Fix planning on resume list refresh

- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/PlanModuleController.java
- app/src/main/java/org/eyeseetea/malariacare/views/CustomSpinner.java
- app/src/main/res/layout/tab_plan_layout.xml
> fixed monitoring filters

- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
> Fix blocked surveyfragment asyntask

- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedPerOrgUnitFragment.java
> Bug planning orgunit checkbox

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/file_paths.xml
- build.gradle
> Feature image intent

- app/src/main/java/org/eyeseetea/malariacare/VideoActivity.java
> Feature video rotation

- app/build.gradle
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedFragment.java
- app/src/main/res/layout/tab_dashboard.xml
- build.gradle
> Remove new PlanningOrgUnit view

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
closes #1206
Added:
Validation of Composite scores
-If a composite score not have hirearchical code or has childrens but not questions, it will be removed.
-If a composite score not have parent and is not root, show a log message in the console.
> Feature composite score validation

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java
> Bug match doesnt work

- app/src/main/res/layout/date.xml
> Change CustomEditText component on date types by a CustomButton

- app/src/main/java/org/eyeseetea/malariacare/sdk/SdkPullController.java
- app/src/main/res/values/donottranslate.xml
Pull of programs with DESCENDANTS download programs and children, not is necessary request children individually
> optimize pull of programs and orunits calls to api

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/datasources/ConversionLocalDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/DataValueExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/OrganisationUnitExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/ProgramStageExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PullDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/SdkQueries.java
- app/src/main/java/org/eyeseetea/malariacare/domain/exception/ConversionException.java
Introduce fields:
code in DataElementFLow
path in OrganisationUnitExtended
Methods:
DataValueExtended:
setProvidedElsewhere Removed
getEvent() fixed
EventExtended:
setFromServer Removed
getDataValues() Fixed
ProgramStageExtended
getProgramStageSections() Fixed
getProgramStageDataElements() Fixed
> Polish 2.25 getters

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
> Feature new sdk clean login activity

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
> Simplify Progress Activity, delete code related to push action

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Header.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Tab.java
> Feature new sdk fix queries

- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PullDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/pull/PullFilters.java
Closes [88](https://github.com/EyeSeeTea/dhis2-android-sdk/issues/88) (sdk issue)
[sdk branch](https://github.com/EyeSeeTea/dhis2-android-sdk/tree/2.25-EyeSeeTea-new_event_variables)
> Add variables in pull event

- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/DataElementExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/OptionExtended.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/SdkQueries.java
> Review some fixme. Fix having queries, improve findProgramStageSection

- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/planning/SurveyPlanner.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/AssessModuleController.java
Closes #1281 
-Fixed a bug setting the main Score in the Planned survey on delete.
-Fixed a bug when a survey with compulsory is not completed, or when its completed out from improve tab.
This feature needs the sdk branch: [EyeSeeTea_fix_push](https://github.com/EyeSeeTea/dhis2-android-sdk/tree/2.25-EyeSeeTea_fix_push)
> Feature new sdk delete survey bug

- app/build.gradle
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/ExportData.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PullDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PushDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/SdkController.java
- app/src/main/java/org/eyeseetea/malariacare/domain/boundary/IPushController.java
- app/src/main/java/org/eyeseetea/malariacare/domain/exception/SurveysToPushNotFoundException.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/PushUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/pull/PullUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
- app/src/test/java/org/eyeseetea/malariacare/domain/usecase/PushUseCaseTest.java
> Feature test push use case inprogress

- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/importer/models/DataElementExtended.java
Closes #1297 
Added "description" field 
Sdk branch: [2.25-EyeSeeTea_add_feedback](https://github.com/EyeSeeTea/dhis2-android-sdk/tree/2.25-EyeSeeTea_add_feedback)
> Fix feedback field

- app/build.gradle
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/VideoActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/PlannedPerOrgUnitFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
> Added language preference

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
> Fix null on refresh metadata demo push

- app/src/main/res/layout/tab_improve_layout.xml
> Fix improve filter size

- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Permissions.java
> Added android 6permissions

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DownloadedMediaActivity.java
> Added menu in downloaded media

- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
Closes #1324 
This only removes duplicate code
> Remove duplciate controldataelement

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration13addUserColumns.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/User.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/network/NetworkUtils.java
- app/src/main/java/org/eyeseetea/malariacare/network/PullClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/QueryFormatterUtils.java
- app/src/main/java/org/eyeseetea/malariacare/utils/AUtils.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-my/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
> Feature announcement

- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PushDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
> Fix bug with dates in quarantinecheck

- app/src/main/res/layout/image_org_unit_filter_item.xml
- app/src/main/res/layout/image_program_filter_item.xml
- app/src/main/res/layout/tab_improve_layout.xml
- app/src/main/res/layout/tab_plan_layout.xml
Closes #1342 
@ifoche the filters size are equals now, and 50% 50% of the screen, but the spinner text alignment is centered, and maybe is it a problem?
I tried to change the spinner text alignment but i couldn't get it in time.
> Little refactor and make the filters 50%50%

- app/src/main/java/org/eyeseetea/malariacare/drive/DownloadMediaTask.java
> Show synced toast only if the number of synces files is 1 or more

- app/src/main/res/layout/score.xml
> modify num/denum space and color in surveyFragment layout

- app/src/main/java/org/eyeseetea/malariacare/data/database/datasources/UserAccountLocalDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabViewHolder.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/main/res/layout/date.xml
- app/src/main/res/layout/ddl.xml
- app/src/main/res/layout/ddl_scored.xml
- app/src/main/res/layout/dev_custom_action_bar.xml
- app/src/main/res/layout/feedback_question_row.xml
- app/src/main/res/layout/integer.xml
- app/src/main/res/layout/label.xml
- app/src/main/res/layout/longtext.xml
- app/src/main/res/layout/question_row.xml
- app/src/main/res/layout/question_uid.xml
- app/src/main/res/layout/radio.xml
- app/src/main/res/layout/radio_scored.xml
- app/src/main/res/layout/shorttext.xml
- app/src/main/res/layout/switchbutton.xml
- app/src/main/res/values/donottranslate.xml
> Feature new developer options

- app/src/eds/java/org/eyeseetea/malariacare/utils/Permissions.java
- app/src/hnqis/java/org/eyeseetea/malariacare/utils/Permissions.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/metadata/PhoneMetaData.java
> Feature make android6 compatible in 2.22 branch

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabViewHolder.java
- app/src/main/res/layout/date.xml
- app/src/main/res/layout/ddl.xml
- app/src/main/res/layout/ddl_scored.xml
- app/src/main/res/layout/integer.xml
- app/src/main/res/layout/label.xml
- app/src/main/res/layout/longtext.xml
- app/src/main/res/layout/radio.xml
- app/src/main/res/layout/radio_scored.xml
- app/src/main/res/layout/shorttext.xml
- app/src/main/res/layout/switchbutton.xml
Closes #1372 
Important for test:
The uid link doesn't open with the demo user( demo.mode://api/dataElements/uid is not valid url)
> Move question uid to statement

- app/src/eds/res/raw/settings.json
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ExportData.java
> Feature make work export db in 2.22 compatibility branch

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/layout/score/ScoreRegister.java
> Bug 2.22 compatibility score register

- app/src/eds/java/org/eyeseetea/malariacare/migrations/Migration10RemoveTabGroups.java
- app/src/eds/java/org/eyeseetea/malariacare/migrations/Migration12UpdateEdsTables.java
- app/src/eds/java/org/eyeseetea/malariacare/migrations/Migration9RenameTables.java
- app/src/hnqis/java/org/eyeseetea/malariacare/database/migrations/Migration11RemoveTabGroups.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/MigrationUtils.java
> Fix eds migration

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ExportData.java
> Remove the remove of compressedData file on activity on result fix gmail

- app/src/eds/res/layout/label.xml
> Fix eds label background

- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
> Ignore the filters on SentDashboard if is not active in JSON

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/network/NetworkUtils.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Closes #1352 
@ifoche  I didn't find "commits" with blank and duplicates out of this branch.
But if the entire quarantine / sending states workflow was missing, y repase and add all the changes from the code from the last version.
> Bugs 2.22 compatibility duplicate and blanks

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Filter sentsurveyslist, use only last survey by program and org unit

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
> Set sending survey as quarantine whe the app starts

- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
> Fix is network available or is push in porgress==false to push.

- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
> Fix bug when the surveyChecker check the quarentine on emtpy server

- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> revert sent survey list to show all the sent surveys

- app/src/eds/res/values/donottranslate
- app/src/hnqis/res/values/donottranslate.xml
- app/src/surveillance/res/values/donottranslate.xml
> Feature modify dhis autority by variant

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Closes #1422 
I moved the wipeData to be used by all the logout subscribes..(logout subscribe in settingactivity and in progressactivity never called this function)
> Single popup on logout and refresh metadata without push of events

- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/ImproveModuleController.java
> prevent background null on null filters

- app/src/main/res/layout/create_survey_fragment.xml
- app/src/main/res/values/dimens.xml
> Bug 2.22 creation label padding

- app/src/eds/res/values/donottranslate.xml
> change eds name and default server

- app/src/eds/res/xml/pref_general.xml
> Remove hide_planning from eds preferences

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/dashboard/controllers/AssessModuleController.java
> Fix list workflow in eds

- app/src/main/res/layout/radio.xml
- app/src/main/res/layout/radio_scored.xml
> Added more space for checkbox answer

- app/src/main/res/layout/feedback.xml
> fix quality of care text size

- app/src/main/res/layout/feedback_composite_score_row.xml
> Fix feedback header not visible score

- app/src/main/java/org/eyeseetea/malariacare/fragments/FeedbackFragment.java
> use always the same format in feedback main cs

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
> Fix uploadedBy username instead of user

- app/src/eds/res/xml/pref_general.xml
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/VideoActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
> Feature 2.22 multilanguage

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
> Feature 2.22 compatibility fix dates controldataelemnets

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/ExportData.java
> Bug export db gmail fails

- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
Closes https://github.com/EyeSeeTea/pictureapp/issues/1088
> fix surveyChecker on empty server

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
> set sending surveys as quarantine on start

- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
> Bug duplicate question forms

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/FeedbackAdapter.java
- app/src/main/res/layout/feedback_question_row.xml
> fix click area on feedback row

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Fix sentfragment  order and increase performance

- app/src/eds/res/values-es/strings.xml
- app/src/eds/res/values-fr/strings.xml
- app/src/eds/res/values-pt/strings.xml
- app/src/eds/res/values/strings.xml
- app/src/hnqis/res/values-es/strings.xml
- app/src/hnqis/res/values-fr/strings.xml
- app/src/hnqis/res/values-km/strings.xml
- app/src/hnqis/res/values-pt/strings.xml
- app/src/hnqis/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Permissions.java
- app/src/main/res/values-my/strings.xml
Closes #1458 
I added the fixed permissions bug on android 7 to make it work in all devices.
> Feature remove push before pull

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/IConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/iomodules/dhis/exporter/VisitableToSDK.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/domain/exception/ConversionException.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/PushUseCase.java
> Feature show conversion error and push bugs

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
> Feature move alarm

- app/src/main/java/org/eyeseetea/malariacare/layout/utils/AutoTabLayoutUtils.java
> fixed blank question form

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/network/NetworkUtils.java
- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
> Bug 2.22 compatibility fix survey checker and timeout

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
> Bug survey dissappearing after sending

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
> Fix surveys dissapearing  after sending them

- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/monitor/Facility/FacilityTableDataByOrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/monitor/Facility/FacilityTableDataByProgram.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/monitor/Pie/PieDataByOrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/monitor/Pie/PieDataByProgram.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/monitor/allassessments/EntrySentSurveysChartByOrgUnit.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/monitor/allassessments/EntrySentSurveysChartByProgram.java
- app/src/main/java/org/eyeseetea/malariacare/utils/AUtils.java
> Added method to escape program name and  orgUnit name in monitoring
